[phases.setup]
nixPkgs = ["python310", "libGL", "pkg-config", "glib", "libxkbcommon", "mesa", "xorg.libX11", "xorg.libXext", "xorg.libXrender"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"
