[phases.setup]
nixPkgs = ["python310Full", "python310Packages.pip"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install --upgrade pip",
  "/app/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/gunicorn main:app --bind 0.0.0.0:$PORT"
