[phases.setup]
nixPkgs = ["python310", "libGL", "pkg-config", "glib", "libxkbcommon", "mesa", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "curl"]

[phases.install]
cmds = [
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"
