[phases.setup]
nixPkgs = ["python310Full", "python310Packages.pip"]

[phases.install]
cmds = [
  "python -m venv /app/venv",
  ". /app/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install gunicorn",
  "pip list"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"
