[phases.setup]
nixPkgs = [
  "python310Full",  # Ensures pip and full stdlib
  "libGL",
  "pkg-config",
  "glib",
  "libxkbcommon",
  "mesa",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender"
]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",  # ✅ reliable
  "python3 -m pip install -r requirements.txt"  # ✅ reliable
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"
