[phases.setup]
nixPkgs = [
  "python310Full",
  "python310Packages.pip"
]

[phases.install]
cmds = [
  "pip install --no-cache-dir -U pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"
