services:
  - type: web
    name: agronexus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
    plan: free
    memory: 512 